# Set Jekyll Theme
remote_theme: pages-themes/modernist@v0.2.0  # Example theme
plugins:
  - jekyll-remote-theme

# Include custom layouts and CSS files
include:
  - _layouts
  - assets/css
  - assets/css/style.css  # Make sure CSS is included properly